ARG PORT=443
FROM cypress/browsers:node16.16.0-chrome106-ff102-edge as base

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-dev && \
    apt-get clean

# Set work directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy app source code
COPY . .

# Expose port
EXPOSE $PORT

# Run your app with Flask
CMD ["python3", "app.py"]
